# Generated by Django 4.2.1 on 2023-06-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_post_view_count_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
